### ISSUE TITLE
Spruz is incompatible with Rails

### ISSUE THREAD

**Issue by al2o3cr** [flori/spruz#3]
It should probably be mentioned somewhere that loading Spruz can cause Rails to fail in obscure ways, as the definition of Object#try overwrites the ActiveSupport version.

**Comment by flori** [comment]
Thanks for reporting the issue.

This only happened, if you required 'spruz/xt' or 'spruz/xt/try'. It's possible to control, what's extended by only requiring the desired extensions, for example require 'spruz/xt/full'. Renamed "try" to "attempt" now, so this shouldn't be a problem anymore in version >= 0.2.5, because I want the set of extensions in 'spruz/xt' to work with as few complications as possible.
